Feature/video reward for button click (#28)
* Copied InfoBox to create VideoRewardBox

Copied js, CSS, and html/php from InfoBox to create VideoRewardBox for the video reward feature.
Changed up some names to make the functions correspond correctly.

Upcoming: Removing unnecessery functionality and elements, adding newly required functionality and elements

* Trying to use newly made placeVideoRewardBox() and ShowVideoRewardBox

Trying to use the new placeVideoRewardBox() and ShowVideoRewardBox() functions, but this throws an error

co2ok-plugin.js?plugin_version=1.0.2.3&ver=4.9.5:153 Uncaught TypeError: _this.placeVideoRewardBox is not a function

* Gif/video feature works

Gif/Video box appears and video starts when the button is pressed and checked.
The video box disappears when the video ended.
It works for both Default and Minimal button design.
The only minor problem I can currently find is that the size of the box around the video on Mobile isn't correct.

Still needs to be done: Randomizer for several video's
Possibly a fade out for the videobox, rather than a quick removal.

* Added video randomizer for video reward

Added video randomizer functionality for the video reward.
Removed unnecessary //commented code from javascript file.

This doesn't change the original functionality, but makes it ready for added video's in the future

* Added extra video's to the video reward feature

New video's added in the image folder and in the rewardVideo array